_target_: src.model.HiFiGAN
g_hidden_channels: 64
g_upsample_kernel_sizes: [16, 16, 4, 4]
g_residual_kernel_sizes: [3, 7, 11]
g_residual_dilations: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
mpd_periods: [2, 3, 5, 7, 11]
mpd_channels: [16, 64, 256, 512, 512]
mpd_kernel_size: 5
mpd_stride: 3
msd_scales: [1, 2, 4]
msd_channels: [64, 64, 128, 256, 512, 512, 512]
msd_kernel_sizes: [15, 41, 41, 41, 41, 41, 5]
msd_strides: [1, 2, 2, 4, 4, 1, 1]
msd_groups_sizes: [1, 4, 16, 16, 16, 16, 1]
msd_norms:
  - _target_: hydra.utils.get_method
    path: torch.nn.utils.parametrizations.spectral_norm
  - _target_: hydra.utils.get_method
    path: torch.nn.utils.parametrizations.weight_norm
  - _target_: hydra.utils.get_method
    path: torch.nn.utils.parametrizations.weight_norm
