defaults:
  - model: hifigan-v2
  - writer: wandb
  - metrics: metrics
  - dataloader: hifigan-v2
  - datasets: ljspeech
  - transforms: transforms
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01
lr_scheduler: null
loss_function:
  generator:
    _target_: src.loss.GeneratorLoss
  discriminator:
    _target_: src.loss.DiscriminatorLoss
trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: null
  device_tensors: ["wav"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
