train:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  num_workers: 4
  pin_memory: True
  collate_fn:
    _target_: src.datasets.collate.get_collate_fn
    unpad: true
    max_length: 44288 # must be divisible by hop_length

inference:
  _target_: torch.utils.data.DataLoader
  batch_size: 8
  num_workers: 1
  pin_memory: True
  collate_fn:
    _target_: src.datasets.collate.get_collate_fn
    unpad: false
