_target_: src.logger.WandBWriter
project_name: "hifigan"
entity: null
run_name: "testing"
mode: "online"
loss_names:
  - "generator_loss"
  - "discriminator_loss"
  - "g_adv_loss"
  - "g_mel_loss"
  - "g_fm_loss"
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
